const { HEMISPHERE } = require('../hemisphere');
const { MONTHS_INDEXES } = require('../months');

const SEASONS = {
    SPRING: 'spring',
    WINTER: 'winter',
    SUMMER: 'summer',
    AUTUMN: 'autumn',
};

const SEASONS_MAP = {
    [HEMISPHERE.NORTHERN]: {
        [MONTHS_INDEXES.MARCH]: SEASONS.SPRING,
        [MONTHS_INDEXES.APRIL]: SEASONS.SPRING,
        [MONTHS_INDEXES.MAY]: SEASONS.SPRING,

        [MONTHS_INDEXES.JUNE]: SEASONS.SUMMER,
        [MONTHS_INDEXES.JULY]: SEASONS.SUMMER,
        [MONTHS_INDEXES.AUGUST]: SEASONS.SUMMER,

        [MONTHS_INDEXES.SEPTEMBER]: SEASONS.AUTUMN,
        [MONTHS_INDEXES.OCTOBER]: SEASONS.AUTUMN,
        [MONTHS_INDEXES.NOVEMBER]: SEASONS.AUTUMN,

        [MONTHS_INDEXES.DECEMBER]: SEASONS.WINTER,
        [MONTHS_INDEXES.JANUARY]: SEASONS.WINTER,
        [MONTHS_INDEXES.FEBRUARY]: SEASONS.WINTER,
    },

    [HEMISPHERE.SOUTHERN]: {
        [MONTHS_INDEXES.MARCH]: SEASONS.AUTUMN,
        [MONTHS_INDEXES.APRIL]: SEASONS.AUTUMN,
        [MONTHS_INDEXES.MAY]: SEASONS.AUTUMN,

        [MONTHS_INDEXES.JUNE]: SEASONS.WINTER,
        [MONTHS_INDEXES.JULY]: SEASONS.WINTER,
        [MONTHS_INDEXES.AUGUST]: SEASONS.WINTER,

        [MONTHS_INDEXES.SEPTEMBER]: SEASONS.SPRING,
        [MONTHS_INDEXES.OCTOBER]: SEASONS.SPRING,
        [MONTHS_INDEXES.NOVEMBER]: SEASONS.SPRING,

        [MONTHS_INDEXES.DECEMBER]: SEASONS.SUMMER,
        [MONTHS_INDEXES.JANUARY]: SEASONS.SUMMER,
        [MONTHS_INDEXES.FEBRUARY]: SEASONS.SUMMER,
    },
};

module.exports = {
    SEASONS,
    SEASONS_MAP,
};